// seed.go 承载 OAS 初始化/种子逻辑（自 cmd/oas/main.go 下沉，OAS-CONSOLE-09 A1-3）。
// 执行时机基线（A0 seed-behavior.txt）：每次启动无条件执行，函数内部幂等；
// 调用点保持 main() 原位置与顺序：AutoMigrate → SeedDefaultOAuthClients → SeedRBACPolicies → SeedTestUsers。
package oas

import (
	"fmt"
	"os"
	"strings"
	"time"

	"golang.org/x/crypto/bcrypt"
	"gorm.io/gorm"

	oasmodel "ziway/backend/internal/oas/model"
	"ziway/backend/pkg/envpolicy"
	"ziway/backend/pkg/password"

	"go.uber.org/zap"
)

// hashSecret hashes a secret string using bcrypt
func hashSecret(secret string) string {
	hash, _ := bcrypt.GenerateFromPassword([]byte(secret), bcrypt.DefaultCost)
	return string(hash)
}

// SeedDefaultOAuthClients 在 DEV/BETA 档注入默认 OAuth 测试客户端（原 main() 内联块，OAS-CONSOLE-09 A1-3）。
// 执行时机与拆分前一致：main() 依赖初始化后、路由注册前调用。
func SeedDefaultOAuthClients(database *gorm.DB, log *zap.Logger, oasEnv envpolicy.Environment) {
	if !envpolicy.IsQuickLoginEnabled(oasEnv) {
		return
	}
	var clientCount int64
	database.Model(&oasmodel.OAuthClient{}).Count(&clientCount)
	if clientCount == 0 {
		// Seed default OAuth clients for testing
		defaultClients := []oasmodel.OAuthClient{
			{
				ClientID:     "oas-console",
				ClientName:   "OAS Console",
				ClientSecret: hashSecret("oas-console-secret"),
				RedirectURI:  "http://localhost:5000/callback,https://62j75kfyn3.coze.site/callback",
				Scopes:       "openid,profile,email",
				Status:       "active",
				CreatedBy:    "system",
			},
			{
				ClientID:     "booth-app",
				ClientName:   "Booth Application",
				ClientSecret: hashSecret("booth-secret"),
				RedirectURI:  "http://localhost:3000/auth/callback",
				Scopes:       "openid,profile",
				Status:       "active",
				CreatedBy:    "system",
			},
		}
		for _, client := range defaultClients {
			database.Create(&client)
		}
		log.Info("OAuth clients seeded", zap.Int("count", len(defaultClients)))
	}
}

// RegeneratePolicyCSV reads all active oasmodel.RBACPolicy from DB and writes the Casbin-compatible CSV.
func RegeneratePolicyCSV(database *gorm.DB, log *zap.Logger) {
	var policies []oasmodel.RBACPolicy
	database.Where("policy_type = ? AND status = ?", "rbac", "active").
		Order("subject, resource").Find(&policies)

	path := "configs/rbac_policy.csv"
	var sb strings.Builder
	sb.WriteString("# RBAC Policy — auto-generated by OAS (authority source)\n")
	sb.WriteString("# Format: p, <subject>, <resource>, <action>\n")
	sb.WriteString("# Role inheritance: g, <user_or_role>, <parent_role>\n\n")

	for _, p := range policies {
		sb.WriteString(fmt.Sprintf("p, %s, %s, %s\n", p.Subject, p.Resource, p.Action))
	}

	// Write role hierarchy (g lines) for 12U + CX/FX + NHI
	sb.WriteString("\n# === Role hierarchy (12U governance chain) ===\n")
	roleHierarchy := map[string]string{
		"CX": "HU", "FX": "FU",
	}
	for child, parent := range roleHierarchy {
		sb.WriteString(fmt.Sprintf("g, %s, %s\n", child, parent))
	}

	if err := os.WriteFile(path, []byte(sb.String()), 0644); err != nil {
		log.Error("failed to regenerate policy CSV", zap.Error(err))
		return
	}
	log.Info("policy CSV regenerated", zap.String("path", path), zap.Int("rules", len(policies)))
}

// SeedRBACPolicies seeds the default 12U + CX/FX + NHI policies if the table is empty.
func SeedRBACPolicies(database *gorm.DB, log *zap.Logger) {
	var count int64
	database.Model(&oasmodel.RBACPolicy{}).Where("policy_type = ?", "rbac").Count(&count)
	if count > 0 {
		return
	}

	type seedRow struct {
		subject, resource, action, roleType, domain string
	}

	seeds := []seedRow{
		// SU — SystemUser: full access
		{"SU", "/api/v1/*", "*", "base", "*"},
		// OU — OwnerUser: full access on owner plane
		{"OU", "/api/v1/owner/*", "*", "base", "*"},
		{"OU", "/api/v1/bos/*", "*", "base", "*"},
		// AU — AdminUser: read+write on admin plane
		{"AU", "/api/v1/admin/*", "*", "base", "*"},
		{"AU", "/api/v1/bos/*/proxy/*", "*", "base", "*"},
		// GU — GovernanceUser: read governance
		{"GU", "/api/v1/owner/policies", "GET", "base", "*"},
		{"GU", "/api/v1/bos/gos/*", "GET", "base", "*"},
		{"GU", "/api/v1/bos/oos/*", "GET", "base", "*"},
		// FU — FinancialUser: financial resources
		{"FU", "/api/v1/bos/dos/daily/*", "*", "base", "*"},
		{"FU", "/api/v1/bos/fos/*", "*", "base", "*"},
		// VU — VCaseUser: operations overview
		{"VU", "/api/v1/bos/vos/*", "*", "base", "*"},
		// IU — InvestmentUser: investment resources
		{"IU", "/api/v1/bos/ios/*", "*", "base", "*"},
		// DU — DomainUser: domain-scoped read
		{"DU", "/api/v1/bos/*/proxy/*", "GET", "base", "*"},
		{"DU", "/api/v1/bos/*/proxy/*", "POST", "base", "*"},
		// HU — HumanUser: basic read
		{"HU", "/api/v1/bos/*", "GET", "base", "*"},
		// CU — CustomerUser: customer-scoped read
		{"CU", "/api/v1/bos/cos/*", "GET", "base", "*"},
		// PU — PartnerUser: partner resources
		{"PU", "/api/v1/bos/eos/*", "*", "base", "*"},
		// EU — EmployeeUser: employee resources
		{"EU", "/api/v1/bos/hos/*", "*", "base", "*"},
		// EM — EnterpriseManager: supply chain management (C1)
		{"EM", "/api/v1/bos/*", "*", "base", "*"},
		{"EM", "/api/v1/os/*/proxy/*", "*", "base", "*"},
		// Hat roles
		{"CX", "/api/v1/bos/cos/*", "*", "hat", "*"},
		{"CX", "/api/v1/bos/dos/*", "*", "hat", "*"},
		{"FX", "/api/v1/bos/fos/*", "*", "hat", "*"},
		{"FX", "/api/v1/bos/dos/daily/*", "*", "hat", "*"},
		// NHI — Non-Human Identity (Agent runtime)
		{"NHI", "/api/v1/bos/*/proxy/*", "GET", "nhi", "*"},
		{"NHI", "/api/v1/bos/*/proxy/*", "POST", "nhi", "*"},
	}

	for _, s := range seeds {
		database.Create(&oasmodel.RBACPolicy{
			PolicyType: "rbac",
			Subject:    s.subject,
			Resource:   s.resource,
			Action:     s.action,
			Effect:     "allow",
			Domain:     s.domain,
			RoleType:   s.roleType,
			Version:    "v1",
			Status:     "active",
			CreatedBy:  "system-seed",
		})
	}

	log.Info("RBAC seed policies created", zap.Int("count", len(seeds)))
	RegeneratePolicyCSV(database, log)
}

// seedTestUser creates a test user with bcrypt-hashed password if no users exist.
// SeedTestUsers creates test accounts based on product edition.
// Beta edition: multiple test accounts with different roles (SU/AU/CU/GU)
// Production edition: only admin account
// Admin accounts (oas-ou-admin, oas-au-admin) are always created.
func SeedTestUsers(database *gorm.DB, log *zap.Logger, edition string) {
	hash, err := password.Hash("test123")
	if err != nil {
		log.Error("failed to hash test password", zap.Error(err))
		return
	}
	hashStr := string(hash)

	// 最高管理者账号（始终创建，用于用户管理接口鉴权）
	adminAccounts := []struct {
		UserCode     string
		Username     string
		DisplayName  string
		IdentityType string
		RoleCode     string
		RoleName     string
	}{
		// OAS-CONSOLE-08: 治理帽显示名对齐生态语言
		{UserCode: "XHPZ#OU-ADMIN", Username: "oas-ou-admin", DisplayName: "系统总管理者", IdentityType: "OU", RoleCode: "SU", RoleName: "System User"},
		{UserCode: "XHPZ#AU-ADMIN", Username: "oas-au-admin", DisplayName: "系统运营管理者", IdentityType: "AU", RoleCode: "AU", RoleName: "AU User"},
		{UserCode: "XHPZ#OAM-ADMIN", Username: "oas-oam-admin", DisplayName: "治理审计员", IdentityType: "OAM", RoleCode: "OAM", RoleName: "OAM User"},
		// OAS-CONSOLE-08: 新增 OU 本人入口（L0 治理看板）
		{UserCode: "XHPZ#OU-OWNER", Username: "oas-ou-owner", DisplayName: "生态董事长", IdentityType: "OU", RoleCode: "OU", RoleName: "OU User"},
	}

	// 确保 SU/AU/OU/OAM 角色存在
	var suRole oasmodel.OASRole
	database.Where("role_code = ?", "SU").First(&suRole)
	if suRole.ID == 0 {
		suRole = oasmodel.OASRole{RoleCode: "SU", Name: "System User", Description: "System User role"}
		database.Create(&suRole)
	}
	var auRole oasmodel.OASRole
	database.Where("role_code = ?", "AU").First(&auRole)
	if auRole.ID == 0 {
		auRole = oasmodel.OASRole{RoleCode: "AU", Name: "AU User", Description: "AU User role"}
		database.Create(&auRole)
	}
	// OAS-CONSOLE-08: 新增 OU 角色（生态董事长）
	var ouRole oasmodel.OASRole
	database.Where("role_code = ?", "OU").First(&ouRole)
	if ouRole.ID == 0 {
		ouRole = oasmodel.OASRole{RoleCode: "OU", Name: "OU User", Description: "Organization Unit User role"}
		database.Create(&ouRole)
	}
	var oamRole oasmodel.OASRole
	database.Where("role_code = ?", "OAM").First(&oamRole)
	if oamRole.ID == 0 {
		oamRole = oasmodel.OASRole{RoleCode: "OAM", Name: "OAM User", Description: "OAM User role"}
		database.Create(&oamRole)
	}

	// OAS-CONSOLE-08: 冻结 XAM 域管理角色 seed（TAM/HAM/YAM/VAM）
	// 已存在的 XAM 角色保留，但不再创建新角色
	// xamRoles := []struct {
	// 	Code        string
	// 	Name        string
	// 	Description string
	// 	Permissions string
	// }{
	// 	{Code: "TAM", Name: "Technology Admin", Description: "技术域管理员", Permissions: `["tam:org:read","tam:org:manage","tam:member:read","tam:member:manage"]`},
	// 	{Code: "HAM", Name: "HR Admin", Description: "人资云管理员", Permissions: `["ham:org:read","ham:org:manage","ham:member:read","ham:member:manage"]`},
	// 	{Code: "YAM", Name: "Smart Plaza Admin", Description: "智场域管理员", Permissions: `["yam:org:read","yam:org:manage","yam:member:read","yam:member:manage"]`},
	// 	{Code: "VAM", Name: "Operations Admin", Description: "运营域管理员", Permissions: `["vam:org:read","vam:org:manage","vam:member:read","vam:member:manage"]`},
	// }
	// for _, xr := range xamRoles {
	// 	var existing oasmodel.OASRole
	// 	database.Where("role_code = ?", xr.Code).First(&existing)
	// 	if existing.ID == 0 {
	// 		role := oasmodel.OASRole{
	// 			RoleCode:    xr.Code,
	// 			Name:        xr.Name,
	// 			Description: xr.Description,
	// 			Permissions: xr.Permissions,
	// 		}
	// 		if err := database.Create(&role).Error; err == nil {
	// 			log.Info("XAM role created", zap.String("role_code", xr.Code))
	// 		}
	// 	}
	// }

	// 创建管理员账号（如果不存在）
	for _, acc := range adminAccounts {
		var existing oasmodel.OASUser
		database.Where("username = ?", acc.Username).First(&existing)
		// 找到对应的角色
		var targetRole oasmodel.OASRole
		database.Where("role_code = ?", acc.RoleCode).First(&targetRole)
		if targetRole.ID == 0 {
			log.Error("role not found for admin account", zap.String("username", acc.Username), zap.String("role_code", acc.RoleCode))
			continue
		}
		if existing.ID == 0 {
			user := oasmodel.OASUser{
				UserCode:     acc.UserCode,
				Username:     acc.Username,
				PasswordHash: hashStr,
				DisplayName:  acc.DisplayName,
				IdentityType: acc.IdentityType,
				EntityType:   "H",
				Status:       "active",
				RoleCode:     acc.RoleCode,
			}
			if err := database.Create(&user).Error; err == nil {
				assignment := oasmodel.OASUserRole{UserID: user.ID, RoleID: targetRole.ID, GrantedBy: "system-seed", GrantedAt: time.Now()}
				database.Table("user_roles").Create(&assignment)
				log.Info("admin user created", zap.String("username", acc.Username), zap.String("role_code", acc.RoleCode))
			}
		} else {
			// 更新现有用户的 role_code 和 user_roles
			if existing.RoleCode != acc.RoleCode {
				database.Model(&existing).Update("role_code", acc.RoleCode)
				log.Info("admin user role_code updated", zap.String("username", acc.Username), zap.String("role_code", acc.RoleCode))
			}
			// 更新 user_roles 表
			var existingAssignment oasmodel.OASUserRole
			database.Where("user_id = ?", existing.ID).First(&existingAssignment)
			if existingAssignment.RoleID != targetRole.ID {
				database.Model(&existingAssignment).Update("role_id", targetRole.ID)
				log.Info("admin user role updated", zap.String("username", acc.Username), zap.Uint64("role_id", targetRole.ID))
			}
		}
	}

	// OAS-CONSOLE-08: 禁用现有 XAM 域管理账号（TAM/HAM/YAM/VAM）
	// 不物理删除，仅设置 status=disabled
	xamRoleCodes := []string{"TAM", "HAM", "YAM", "VAM"}
	for _, roleCode := range xamRoleCodes {
		// 查找该角色对应的 role_id
		var xamRole oasmodel.OASRole
		if err := database.Where("role_code = ?", roleCode).First(&xamRole).Error; err == nil {
			// 查找该角色下的所有用户
			var xamAssignments []oasmodel.OASUserRole
			database.Where("role_id = ?", xamRole.ID).Find(&xamAssignments)
			for _, assignment := range xamAssignments {
				// 禁用用户
				database.Model(&oasmodel.OASUser{}).Where("id = ?", assignment.UserID).Update("status", "disabled")
				log.Info("XAM user disabled", zap.Uint64("user_id", assignment.UserID), zap.String("role_code", roleCode))
			}
		}
	}

	// Define test accounts (always create if not exist, for quick-login)
	type testAccount struct {
		UserCode     string
		Username     string
		DisplayName  string
		IdentityType string
		RoleCode     string
		RoleName     string
	}

	accounts := []testAccount{
		// 默认测试账号（始终创建，供 quick-login 使用）
		{UserCode: "XHPZ#SU-TEST001", Username: "admin", DisplayName: "系统管理员", IdentityType: "SU", RoleCode: "SU", RoleName: "System User"},
		{UserCode: "XHPZ#AU-TEST001", Username: "operator", DisplayName: "运营人员", IdentityType: "AU", RoleCode: "AU", RoleName: "Admin User"},
		{UserCode: "XHPZ#CU-TEST001", Username: "customer", DisplayName: "客户用户", IdentityType: "CU", RoleCode: "CU", RoleName: "Customer User"},
		{UserCode: "XHPZ#GU-TEST001", Username: "viewer", DisplayName: "访客", IdentityType: "GU", RoleCode: "GU", RoleName: "Guest User"},
		{UserCode: "XHPZ#EM-TEST001", Username: "em", DisplayName: "供给运营长", IdentityType: "EM", RoleCode: "EM", RoleName: "Enterprise Manager"},
	}

	log.Info("seeding test accounts for quick-login")

	// Create roles and users
	for _, acc := range accounts {
		// Create role if not exists
		var role oasmodel.OASRole
		database.Where("role_code = ?", acc.RoleCode).First(&role)
		if role.ID == 0 {
			role = oasmodel.OASRole{
				RoleCode:    acc.RoleCode,
				Name:        acc.RoleName,
				Description: acc.RoleName + " role",
			}
			if err := database.Create(&role).Error; err != nil {
				log.Error("failed to create role", zap.String("role", acc.RoleCode), zap.Error(err))
				continue
			}
			log.Info("role created", zap.String("role_code", acc.RoleCode), zap.Uint64("id", role.ID))
		}

		// Create user
		// Create user if not exists
		var existingUser oasmodel.OASUser
		database.Where("username = ?", acc.Username).First(&existingUser)
		if existingUser.ID == 0 {
			user := oasmodel.OASUser{
				UserCode:     acc.UserCode,
				Username:     acc.Username,
				PasswordHash: hashStr,
				DisplayName:  acc.DisplayName,
				IdentityType: acc.IdentityType,
				EntityType:   "H",
				Status:       "active",
				RoleCode:     acc.RoleCode,
			}
			if err := database.Create(&user).Error; err != nil {
				log.Error("failed to create user", zap.String("username", acc.Username), zap.Error(err))
				continue
			}

			// Assign role
			assignment := oasmodel.OASUserRole{
				UserID:    user.ID,
				RoleID:    role.ID,
				GrantedBy: "system-seed",
				GrantedAt: time.Now(),
			}
			if err := database.Table("user_roles").Create(&assignment).Error; err != nil {
				log.Error("failed to assign role", zap.String("username", acc.Username), zap.Error(err))
			} else {
				log.Info("test user created", zap.String("username", acc.Username), zap.String("role", acc.RoleCode))
			}
		} else {
			// User exists, ensure role assignment exists
			var existingAssignment oasmodel.OASUserRole
			database.Where("user_id = ? AND role_id = ?", existingUser.ID, role.ID).First(&existingAssignment)
			if existingAssignment.ID == 0 {
				assignment := oasmodel.OASUserRole{
					UserID:    existingUser.ID,
					RoleID:    role.ID,
					GrantedBy: "system-seed",
					GrantedAt: time.Now(),
				}
				database.Table("user_roles").Create(&assignment)
				log.Info("test user role assignment created", zap.String("username", acc.Username), zap.String("role", acc.RoleCode))
			}
		}
	}

	// Create disabled user for testing 403 response
	hash2, _ := password.Hash("disabled123")
	database.Create(&oasmodel.OASUser{
		UserCode:     "XHPZ#DU-DISABLED",
		Username:     "disabled_user",
		PasswordHash: string(hash2),
		DisplayName:  "Disabled User",
		IdentityType: "DU",
		EntityType:   "H",
		Status:       "disabled",
	})

	log.Info("test users seeded", zap.String("edition", edition), zap.Int("count", len(accounts)))
}
